research_task:
  description: >
    Conduct a thorough research about what {topic} has recently said or wrote.
    This includes any recent tweets, writings, speeches, interviews or public statements.
    Make sure you find any interesting and relevant information given
    the current date is {current_date}.
  expected_output: >
    A list with 10 bullet points ordered by importance of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst


stock_analysis_task:
  description: >
    Based on the research and reporting tasks, analyze expected effects on the stock markets in USA.
    Consider the implications of {topic}'s recent actions, statements, and public perception as given to you in the context.
    Include expected general trends, as wel as specific predictions for specific companies and sectors if relevant.
  expected_output: >
    A detailed analysis of {topic}'s stock market performance, including key metrics, trends, and future predictions.
    Formatted as markdown without '```'
  agent: stock_analyst

investment_task:
  description: >
    Based on the stock analysis, provide recommendations for short-term investments.
    Consider the various sectors expected behavior as mentionsd in the context provided to you.
    Include specific stocks that present opportunities for short-term investments.
  expected_output: >
    A list of recommended short-term investments, including specific stocks and sectors to focus on.
    A separate list of stocks to avoid or to sell as soon as possible.
    Formatted as a JSON with 2 arrays of tickers without '```'
  agent: investment_consultant